In [1]:
import numpy as np

In [102]:
a = np.random.randint(30, size=(4,5,3,3)).reshape(4,5,-1)
#print a
# print a[:,:, -4:]
ind = a.argpartition(-2, axis=2)[:, :, -2:]
print a
col = np.arange(a.shape[0])[:,None,None]
row = np.arange(a.shape[1])[:,None]

print a[col, row, ind]

[[[25 17 18 10 16 15  5  2  1]
  [16  7 24 22 11 19  6 24 21]
  [ 8 20 27 14 28 26 12 22 24]
  [24 24  5 19  0 19  2 29 29]
  [11 29 23  8  5 26  0  8 13]]

 [[21 13 17  9 17 25  7  7 29]
  [ 1 23 15 11 14 20 29 18  1]
  [ 0 22  5  1 13 12  5  4 16]
  [ 5  7  3  1 20 29 28  2 19]
  [14 15  9 15 18  5 25 19  6]]

 [[ 9 10 24 24 10 27 16  0 20]
  [ 8  0  7 16 25 12  5 24 19]
  [24 27 27  9 18 26  9  9  7]
  [15 22 26 15  1  6  2 10 23]
  [ 9  3  7  4  9 13 21  6  9]]

 [[19 29 13 11 29 21  4  8  9]
  [ 9 28 26  1 24  5 16  8  0]
  [20  7 14 18 18 11  3 25  3]
  [24  6  1 26 19 24  0 28  4]
  [15 21 27 25 14  4 28  9 24]]]
[[[18 25]
  [24 24]
  [27 28]
  [29 29]
  [26 29]]

 [[25 29]
  [23 29]
  [16 22]
  [28 29]
  [19 25]]

 [[24 27]
  [24 25]
  [27 27]
  [23 26]
  [13 21]]

 [[29 29]
  [26 28]
  [20 25]
  [26 28]
  [27 28]]]


In [109]:
def get_local_output(input):
        flat_in = input.reshape(input.shape[0], input.shape[1], -1)
        ind = np.argpartition(input, -k)[-k:]

        ind = flat_in.argpartition(-k, axis=2)[:, :, -k:]
        col = np.arange(a.shape[0])[:,None,None]
        row = np.arange(a.shape[1])[:,None]
    
        mask = np.zeros_like(flat_in, dtype=bool)
        mask[col, row, ind] = True
        self_mask = mask.reshape(input.shape)
        return input *self_mask

In [112]:
k=2
print a
print get_local_output(a)

[[[25 17 18 10 16 15  5  2  1]
  [16  7 24 22 11 19  6 24 21]
  [ 8 20 27 14 28 26 12 22 24]
  [24 24  5 19  0 19  2 29 29]
  [11 29 23  8  5 26  0  8 13]]

 [[21 13 17  9 17 25  7  7 29]
  [ 1 23 15 11 14 20 29 18  1]
  [ 0 22  5  1 13 12  5  4 16]
  [ 5  7  3  1 20 29 28  2 19]
  [14 15  9 15 18  5 25 19  6]]

 [[ 9 10 24 24 10 27 16  0 20]
  [ 8  0  7 16 25 12  5 24 19]
  [24 27 27  9 18 26  9  9  7]
  [15 22 26 15  1  6  2 10 23]
  [ 9  3  7  4  9 13 21  6  9]]

 [[19 29 13 11 29 21  4  8  9]
  [ 9 28 26  1 24  5 16  8  0]
  [20  7 14 18 18 11  3 25  3]
  [24  6  1 26 19 24  0 28  4]
  [15 21 27 25 14  4 28  9 24]]]
[[[25  0 18  0  0  0  0  0  0]
  [ 0  0 24  0  0  0  0 24  0]
  [ 0  0 27  0 28  0  0  0  0]
  [ 0  0  0  0  0  0  0 29 29]
  [ 0 29  0  0  0 26  0  0  0]]

 [[ 0  0  0  0  0 25  0  0 29]
  [ 0 23  0  0  0  0 29  0  0]
  [ 0 22  0  0  0  0  0  0 16]
  [ 0  0  0  0  0 29 28  0  0]
  [ 0  0  0  0  0  0 25 19  0]]

 [[ 0  0  0 24  0 27  0  0  0]
  [ 0  0  0  0 25  0  0 24 